version: '3.7'

services:
  web:
    image: robert/express-webpack-react-redux-typescript-boilerplate
    build: # ignored when deploying a stack in swarm mode or kubernetes
      context: .
      args:
        - PORT=${PORT}
    ports:
      - '${PORT}:${PORT}'
    depends_on: # ignored when deploying a stack in swarm mode or kubernetes
      - mongodb
      - redis
    restart: always # ignored when deploying a stack in swarm mode or kubernetes
    deploy: # ignored by docker-compose
      replicas: 3
      restart_policy:
        condition: on-failure

  mongodb:
    image: mongo
    volumes:
      - ./backend/mongodb-data:/data/
    restart: unless-stopped

  redis:
    image: redis:alpine
    volumes:
      - ./backend/redis-data:/data
    restart: unless-stopped
